{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "%run MyNoteBook.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import Valid_Datasets\n",
    "from sklearn.decomposition import PCA\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-b78db6980564>\", line 6, in <module>\n",
      "  File \"c:\\Users\\xiang\\Documents\\GitHub\\Four-Guys-DSGP\\Valid_Datasets.py\", line 150, in KNN_for_watch_data\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pandas\\core\\frame.py\", line 3643, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pandas\\core\\frame.py\", line 3694, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pandas\\core\\frame.py\", line 3721, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3361, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3458, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2944, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3169, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3380, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 762, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 769, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 535, in execute_request\n",
      "    reply_content = yield gen.maybe_future(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 762, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2898, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2949, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1081, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 925, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\traitlets\\config\\application.py\", line 141, in format\n",
      "    return super().format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 672, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 622, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 3 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 374, in dispatch_queue\n",
      "    yield self.process_one()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 762, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 769, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 762, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 769, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 263, in dispatch_shell\n",
      "    self.log.error(\"Exception in message handler:\", exc_info=True)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\n",
      "    self.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\n",
      "    self.emit(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1089, in emit\n",
      "    self.handleError(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1003, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 4 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1081, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 925, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\traitlets\\config\\application.py\", line 141, in format\n",
      "    return super().format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 672, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 622, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 5 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\ioloop.py\", line 765, in _discard_future_result\n",
      "    future.result()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\gen.py\", line 769, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 376, in dispatch_queue\n",
      "    self.log.exception(\"Error in message handler\")\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1469, in exception\n",
      "    self.error(msg, *args, exc_info=exc_info, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\n",
      "    self.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\n",
      "    self.emit(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1089, in emit\n",
      "    self.handleError(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1003, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 6 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1081, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 925, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 672, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 622, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 7 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\ioloop.py\", line 761, in _run_callback\n",
      "    app_log.error(\"Exception in callback %r\", callback, exc_info=True)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\n",
      "    self.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\n",
      "    self.emit(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1089, in emit\n",
      "    self.handleError(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1003, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 8 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1081, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 925, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 672, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 622, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 9 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\base_events.py\", line 1733, in call_exception_handler\n",
      "    self.default_exception_handler(context)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\base_events.py\", line 1707, in default_exception_handler\n",
      "    logger.error('\\n'.join(log_lines), exc_info=exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\n",
      "    self.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\n",
      "    self.emit(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1089, in emit\n",
      "    self.handleError(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1003, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 10 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1081, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 925, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 672, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 622, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 11 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 194, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\traitlets\\config\\application.py\", line 978, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\xiang\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\events.py\", line 95, in _run\n",
      "    self._loop.call_exception_handler(context)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\asyncio\\base_events.py\", line 1740, in call_exception_handler\n",
      "    logger.error('Exception in default exception handler',\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\n",
      "    self.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\n",
      "    self.emit(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1089, in emit\n",
      "    self.handleError(record)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1003, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 103, in print_exception\n",
      "    for line in TracebackException(\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 524, in __init__\n",
      "    self._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 536, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 12 more times]\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 534, in _load_lines\n",
      "    frame.line\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\traceback.py\", line 288, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"c:\\Users\\xiang\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4806: invalid continuation byte\n"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mCanceled future for execute_request message before replies were done"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "instance = Valid_Datasets.get_df('00EABED2-271D-49D8-B599-1D4A09240601')\n",
    "\n",
    "test_example = instance\n",
    "\n",
    "cleaned_data = Valid_Datasets.non_watch_value_imputer(test_example)\n",
    "cleaned_data = Valid_Datasets.KNN_for_watch_data(cleaned_data,10)\n",
    "cleaned_data = Valid_Datasets.pca_to_data(cleaned_data,2)\n",
    "cleaned_data\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['0BFC35E2-4817-4865-BFA7-764742302A2D', '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E', '1155FF54-63D3-4AB2-9863-8385D0BD0A13', '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842', '27E04243-B138-4F40-A164-F40B60165CF3', '00EABED2-271D-49D8-B599-1D4A09240601', '098A72A5-E3E5-4F54-A152-BBDA0DF7B694', '0A986513-7828-4D53-AA1F-E02D6DF9561B', '11B5EC4D-4133-4289-B475-4E737182A406', '136562B6-95B2-483D-88DC-065F28409FD2', '1538C99F-BA1E-4EFB-A949-6C7C47701B20', '24E40C4C-A349-4F9F-93AB-01D00FB994AF']\n"
     ]
    }
   ],
   "source": [
    "print(Valid_Datasets.get_cross_validation('test',0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th>raw_acc:magnitude_stats:mean</th>\n",
       "      <th>raw_acc:magnitude_stats:std</th>\n",
       "      <th>raw_acc:magnitude_stats:moment3</th>\n",
       "      <th>raw_acc:magnitude_stats:moment4</th>\n",
       "      <th>raw_acc:magnitude_stats:percentile25</th>\n",
       "      <th>raw_acc:magnitude_stats:percentile50</th>\n",
       "      <th>raw_acc:magnitude_stats:percentile75</th>\n",
       "      <th>raw_acc:magnitude_stats:value_entropy</th>\n",
       "      <th>raw_acc:magnitude_stats:time_entropy</th>\n",
       "      <th>raw_acc:magnitude_spectrum:log_energy_band0</th>\n",
       "      <th>...</th>\n",
       "      <th>label:STAIRS_-_GOING_DOWN</th>\n",
       "      <th>label:ELEVATOR</th>\n",
       "      <th>label:OR_standing</th>\n",
       "      <th>label:AT_SCHOOL</th>\n",
       "      <th>label:PHONE_IN_HAND</th>\n",
       "      <th>label:PHONE_IN_BAG</th>\n",
       "      <th>label:PHONE_ON_TABLE</th>\n",
       "      <th>label:WITH_CO-WORKERS</th>\n",
       "      <th>label:WITH_FRIENDS</th>\n",
       "      <th>label_source</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <th>timestamp</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th rowspan=\"11\" valign=\"top\">00EABED2-271D-49D8-B599-1D4A09240601</th>\n",
       "      <th>1444079161</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444079221</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444079281</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444079341</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444079431</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444750610</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444750670</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444750731</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444750768</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1444750828</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2287 rows × 277 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                 raw_acc:magnitude_stats:mean  \\\n",
       "                                     timestamp                                  \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                           NaN   \n",
       "                                     1444079221                           NaN   \n",
       "                                     1444079281                           NaN   \n",
       "                                     1444079341                           NaN   \n",
       "                                     1444079431                           NaN   \n",
       "...                                                                       ...   \n",
       "                                     1444750610                           NaN   \n",
       "                                     1444750670                           NaN   \n",
       "                                     1444750731                           NaN   \n",
       "                                     1444750768                           NaN   \n",
       "                                     1444750828                           NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:std  \\\n",
       "                                     timestamp                                 \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                          NaN   \n",
       "                                     1444079221                          NaN   \n",
       "                                     1444079281                          NaN   \n",
       "                                     1444079341                          NaN   \n",
       "                                     1444079431                          NaN   \n",
       "...                                                                      ...   \n",
       "                                     1444750610                          NaN   \n",
       "                                     1444750670                          NaN   \n",
       "                                     1444750731                          NaN   \n",
       "                                     1444750768                          NaN   \n",
       "                                     1444750828                          NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:moment3  \\\n",
       "                                     timestamp                                     \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                              NaN   \n",
       "                                     1444079221                              NaN   \n",
       "                                     1444079281                              NaN   \n",
       "                                     1444079341                              NaN   \n",
       "                                     1444079431                              NaN   \n",
       "...                                                                          ...   \n",
       "                                     1444750610                              NaN   \n",
       "                                     1444750670                              NaN   \n",
       "                                     1444750731                              NaN   \n",
       "                                     1444750768                              NaN   \n",
       "                                     1444750828                              NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:moment4  \\\n",
       "                                     timestamp                                     \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                              NaN   \n",
       "                                     1444079221                              NaN   \n",
       "                                     1444079281                              NaN   \n",
       "                                     1444079341                              NaN   \n",
       "                                     1444079431                              NaN   \n",
       "...                                                                          ...   \n",
       "                                     1444750610                              NaN   \n",
       "                                     1444750670                              NaN   \n",
       "                                     1444750731                              NaN   \n",
       "                                     1444750768                              NaN   \n",
       "                                     1444750828                              NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:percentile25  \\\n",
       "                                     timestamp                                          \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                   NaN   \n",
       "                                     1444079221                                   NaN   \n",
       "                                     1444079281                                   NaN   \n",
       "                                     1444079341                                   NaN   \n",
       "                                     1444079431                                   NaN   \n",
       "...                                                                               ...   \n",
       "                                     1444750610                                   NaN   \n",
       "                                     1444750670                                   NaN   \n",
       "                                     1444750731                                   NaN   \n",
       "                                     1444750768                                   NaN   \n",
       "                                     1444750828                                   NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:percentile50  \\\n",
       "                                     timestamp                                          \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                   NaN   \n",
       "                                     1444079221                                   NaN   \n",
       "                                     1444079281                                   NaN   \n",
       "                                     1444079341                                   NaN   \n",
       "                                     1444079431                                   NaN   \n",
       "...                                                                               ...   \n",
       "                                     1444750610                                   NaN   \n",
       "                                     1444750670                                   NaN   \n",
       "                                     1444750731                                   NaN   \n",
       "                                     1444750768                                   NaN   \n",
       "                                     1444750828                                   NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:percentile75  \\\n",
       "                                     timestamp                                          \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                   NaN   \n",
       "                                     1444079221                                   NaN   \n",
       "                                     1444079281                                   NaN   \n",
       "                                     1444079341                                   NaN   \n",
       "                                     1444079431                                   NaN   \n",
       "...                                                                               ...   \n",
       "                                     1444750610                                   NaN   \n",
       "                                     1444750670                                   NaN   \n",
       "                                     1444750731                                   NaN   \n",
       "                                     1444750768                                   NaN   \n",
       "                                     1444750828                                   NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:value_entropy  \\\n",
       "                                     timestamp                                           \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                    NaN   \n",
       "                                     1444079221                                    NaN   \n",
       "                                     1444079281                                    NaN   \n",
       "                                     1444079341                                    NaN   \n",
       "                                     1444079431                                    NaN   \n",
       "...                                                                                ...   \n",
       "                                     1444750610                                    NaN   \n",
       "                                     1444750670                                    NaN   \n",
       "                                     1444750731                                    NaN   \n",
       "                                     1444750768                                    NaN   \n",
       "                                     1444750828                                    NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_stats:time_entropy  \\\n",
       "                                     timestamp                                          \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                   NaN   \n",
       "                                     1444079221                                   NaN   \n",
       "                                     1444079281                                   NaN   \n",
       "                                     1444079341                                   NaN   \n",
       "                                     1444079431                                   NaN   \n",
       "...                                                                               ...   \n",
       "                                     1444750610                                   NaN   \n",
       "                                     1444750670                                   NaN   \n",
       "                                     1444750731                                   NaN   \n",
       "                                     1444750768                                   NaN   \n",
       "                                     1444750828                                   NaN   \n",
       "\n",
       "                                                 raw_acc:magnitude_spectrum:log_energy_band0  \\\n",
       "                                     timestamp                                                 \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                                          NaN   \n",
       "                                     1444079221                                          NaN   \n",
       "                                     1444079281                                          NaN   \n",
       "                                     1444079341                                          NaN   \n",
       "                                     1444079431                                          NaN   \n",
       "...                                                                                      ...   \n",
       "                                     1444750610                                          NaN   \n",
       "                                     1444750670                                          NaN   \n",
       "                                     1444750731                                          NaN   \n",
       "                                     1444750768                                          NaN   \n",
       "                                     1444750828                                          NaN   \n",
       "\n",
       "                                                 ...  \\\n",
       "                                     timestamp   ...   \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161  ...   \n",
       "                                     1444079221  ...   \n",
       "                                     1444079281  ...   \n",
       "                                     1444079341  ...   \n",
       "                                     1444079431  ...   \n",
       "...                                              ...   \n",
       "                                     1444750610  ...   \n",
       "                                     1444750670  ...   \n",
       "                                     1444750731  ...   \n",
       "                                     1444750768  ...   \n",
       "                                     1444750828  ...   \n",
       "\n",
       "                                                 label:STAIRS_-_GOING_DOWN  \\\n",
       "                                     timestamp                               \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                        NaN   \n",
       "                                     1444079221                        NaN   \n",
       "                                     1444079281                        NaN   \n",
       "                                     1444079341                        NaN   \n",
       "                                     1444079431                        NaN   \n",
       "...                                                                    ...   \n",
       "                                     1444750610                        NaN   \n",
       "                                     1444750670                        NaN   \n",
       "                                     1444750731                        NaN   \n",
       "                                     1444750768                        NaN   \n",
       "                                     1444750828                        NaN   \n",
       "\n",
       "                                                 label:ELEVATOR  \\\n",
       "                                     timestamp                    \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161             NaN   \n",
       "                                     1444079221             NaN   \n",
       "                                     1444079281             NaN   \n",
       "                                     1444079341             NaN   \n",
       "                                     1444079431             NaN   \n",
       "...                                                         ...   \n",
       "                                     1444750610             NaN   \n",
       "                                     1444750670             NaN   \n",
       "                                     1444750731             NaN   \n",
       "                                     1444750768             NaN   \n",
       "                                     1444750828             NaN   \n",
       "\n",
       "                                                 label:OR_standing  \\\n",
       "                                     timestamp                       \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                NaN   \n",
       "                                     1444079221                NaN   \n",
       "                                     1444079281                NaN   \n",
       "                                     1444079341                NaN   \n",
       "                                     1444079431                NaN   \n",
       "...                                                            ...   \n",
       "                                     1444750610                NaN   \n",
       "                                     1444750670                NaN   \n",
       "                                     1444750731                NaN   \n",
       "                                     1444750768                NaN   \n",
       "                                     1444750828                NaN   \n",
       "\n",
       "                                                 label:AT_SCHOOL  \\\n",
       "                                     timestamp                     \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161              NaN   \n",
       "                                     1444079221              NaN   \n",
       "                                     1444079281              NaN   \n",
       "                                     1444079341              NaN   \n",
       "                                     1444079431              NaN   \n",
       "...                                                          ...   \n",
       "                                     1444750610              NaN   \n",
       "                                     1444750670              NaN   \n",
       "                                     1444750731              NaN   \n",
       "                                     1444750768              NaN   \n",
       "                                     1444750828              NaN   \n",
       "\n",
       "                                                 label:PHONE_IN_HAND  \\\n",
       "                                     timestamp                         \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                  NaN   \n",
       "                                     1444079221                  NaN   \n",
       "                                     1444079281                  NaN   \n",
       "                                     1444079341                  NaN   \n",
       "                                     1444079431                  NaN   \n",
       "...                                                              ...   \n",
       "                                     1444750610                  NaN   \n",
       "                                     1444750670                  NaN   \n",
       "                                     1444750731                  NaN   \n",
       "                                     1444750768                  NaN   \n",
       "                                     1444750828                  NaN   \n",
       "\n",
       "                                                 label:PHONE_IN_BAG  \\\n",
       "                                     timestamp                        \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                 NaN   \n",
       "                                     1444079221                 NaN   \n",
       "                                     1444079281                 NaN   \n",
       "                                     1444079341                 NaN   \n",
       "                                     1444079431                 NaN   \n",
       "...                                                             ...   \n",
       "                                     1444750610                 NaN   \n",
       "                                     1444750670                 NaN   \n",
       "                                     1444750731                 NaN   \n",
       "                                     1444750768                 NaN   \n",
       "                                     1444750828                 NaN   \n",
       "\n",
       "                                                 label:PHONE_ON_TABLE  \\\n",
       "                                     timestamp                          \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                   NaN   \n",
       "                                     1444079221                   NaN   \n",
       "                                     1444079281                   NaN   \n",
       "                                     1444079341                   NaN   \n",
       "                                     1444079431                   NaN   \n",
       "...                                                               ...   \n",
       "                                     1444750610                   NaN   \n",
       "                                     1444750670                   NaN   \n",
       "                                     1444750731                   NaN   \n",
       "                                     1444750768                   NaN   \n",
       "                                     1444750828                   NaN   \n",
       "\n",
       "                                                 label:WITH_CO-WORKERS  \\\n",
       "                                     timestamp                           \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                    NaN   \n",
       "                                     1444079221                    NaN   \n",
       "                                     1444079281                    NaN   \n",
       "                                     1444079341                    NaN   \n",
       "                                     1444079431                    NaN   \n",
       "...                                                                ...   \n",
       "                                     1444750610                    NaN   \n",
       "                                     1444750670                    NaN   \n",
       "                                     1444750731                    NaN   \n",
       "                                     1444750768                    NaN   \n",
       "                                     1444750828                    NaN   \n",
       "\n",
       "                                                 label:WITH_FRIENDS  \\\n",
       "                                     timestamp                        \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161                 NaN   \n",
       "                                     1444079221                 NaN   \n",
       "                                     1444079281                 NaN   \n",
       "                                     1444079341                 NaN   \n",
       "                                     1444079431                 NaN   \n",
       "...                                                             ...   \n",
       "                                     1444750610                 NaN   \n",
       "                                     1444750670                 NaN   \n",
       "                                     1444750731                 NaN   \n",
       "                                     1444750768                 NaN   \n",
       "                                     1444750828                 NaN   \n",
       "\n",
       "                                                 label_source  \n",
       "                                     timestamp                 \n",
       "00EABED2-271D-49D8-B599-1D4A09240601 1444079161           NaN  \n",
       "                                     1444079221           NaN  \n",
       "                                     1444079281           NaN  \n",
       "                                     1444079341           NaN  \n",
       "                                     1444079431           NaN  \n",
       "...                                                       ...  \n",
       "                                     1444750610           NaN  \n",
       "                                     1444750670           NaN  \n",
       "                                     1444750731           NaN  \n",
       "                                     1444750768           NaN  \n",
       "                                     1444750828           NaN  \n",
       "\n",
       "[2287 rows x 277 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import gzip\n",
    "import pandas as pd\n",
    "\n",
    "uuid = '00EABED2-271D-49D8-B599-1D4A09240601'\n",
    "user_data_file = 'Datasets/%s.features_labels.csv.gz' % uuid\n",
    "with gzip.open(user_data_file,'rb') as fid:\n",
    "    csv_df = pd.read_csv(fid,delimiter=',', index_col= 0)\n",
    "    csv_df = pd.DataFrame(csv_df,index=pd.MultiIndex.from_product([[uuid],csv_df.index]))\n",
    "    pass\n",
    "csv_df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
